### ISSUE TITLE
C03. Admin List.

### ISSUE THREAD

**Issue by akshay72222** [campusrope/campusrope#7]
## UI
https://www.figma.com/proto/ZSYnRHyrosdeiTA9d7Tkuotj/A1?node-id=38%3A288&viewport=339%2C126%2C0.1776336431503296&scaling=scale-down-width
Feel free to redesign this UI at will.

### Admin lists
As a super admin, I want to see the list of all the admins of CampusRope
 
### Admin Details
As a super admin, I want to view and edit the details of a admin, when i click on the admin name card from the admin list.

**Comment by faiyazuddeen** [comment]
where are the screens for assign tasks ,view and edit admin details
